### ISSUE TITLE
Падения плагина iikoFront (Resto.Front.Api.Host)

### ISSUE THREAD

**Issue by mstryuk** [iiko/front.api.sdk#111]
Здравствуйте,
Я клиент iiko, обращаюсь сюда с просьбой посоветовать, где искать причину падения плагина.
Плагин Resto.Front.Api.Host, после вылета обрубает все связанные сетевые подключения с iikoFront.

Вылеты только при высоких нагрузках iikoFront, используем сразу несколько плагинов (iikoWaiter, iikoOrder) для работы официантов.

Не уверен какую информацию необходимо предоставить, потому прикрепляю логи 
[plugin-iikoOrderServ.log](https://github.com/iiko/front.api.sdk/files/3991604/plugin-iikoOrderServ.log)
[logs.zip](https://github.com/iiko/front.api.sdk/files/3991603/logs.zip)
как видел в похожем кейсе  #15

Надеюсь вы сможете помочь мне с моей проблемой.

[2019-12-21 19:33:46,291] ERROR [50] [ObservableExtensions+<>c__DisplayClass4`2+<>c__DisplayClass6:<CatchToLog>b__3:59] - Exception in “iikoOrderServ” plugin's OnCompleted handler for notification “ProductsRemainingAmountsChanged”: System.Runtime.Remoting.RemotingException: Failed to connect to an IPC Port: Не удается найти указанный файл.
 

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.IObserver`1.OnCompleted()
   at System.Reactive.AutoDetachObserver`1.OnCompletedCore()
   at System.Reactive.ObserverBase`1.OnCompleted()
   at Resto.Front.Api.Extensions.ObservableExtensions.<>c__DisplayClass4`2.<>c__DisplayClass6.<CatchToLog>b__3() in p:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.Front.Api\Extensions\ObservableExtensions.cs:line 59

**Comment by vcpp** [comment]
В первую очередь, хочется предупредить, что данная площадка на github задумана для технического взаимодействия разработчиков плагинов и разработчиков iikoFront API. Площадка открыта для всех, но по умолчанию клиентам при возникновении проблем рекомендуется обращаться в техподдержку, там будут и SLA (здесь нет каких-либо гарантий), и NDA (здесь вы сами опубликовали логи, в которых может содержаться конфиденциальная информация).

> где искать причину падения плагина

Да прямо в логе плагина iikoOrderServ перед его падением:
```
[2019-12-21 19:14:04,483] ERROR [49] - UnhandledException in plugin domain:
System.NullReferenceException: Object reference not set to an instance of an object.
   at WvQcGZJoa3KwSLyJqq.fjFbN9biFS0nTHjLEE.<>c.<Load>b__5_0(Int64 _)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.InvokeStart(IScheduler self, Object state)
```

> Надеюсь вы сможете помочь мне с моей проблемой.

Я бы с радостью, но как? Если бы ошибка была на стороне iikoFront API, я как разработчик iiko мог бы исправить её, но мы же видим, что NRE возникает в обфусцированном коде плагина. Надо чинить плагин.

> используем сразу несколько плагинов (iikoWaiter, iikoOrder) для работы официантов.

Несмотря на наличие *iiko* в названии этих плагинов, технически эти плагины разработаны вне iiko, поэтому вам лучше обратиться в техподдержку, там ваш запрос перенаправят куда следует, и на него ответит специалист, связанный с этими плагинами.

От себя могу рекомендовать обновиться. Вы используете старую версию iikoFront 5.5. Начиная с 6.2 iikoFront [умеет](https://iiko.github.io/front.api.doc/2018/08/20/restart-crashed-plugins.html) автоматически перезапускать падающие плагины. Обновление сразу же сделает работу более удобной — плагин по-прежнему будет падать, но вам для его оживления не придётся перезапускать приложение целиком, вы можете даже не заметить, что плагин падал. Это касается любых плагинов.
Дальше нужно разбираться с конкретным плагином. У вас установлена версия iikoOrderServ v1.50. Возможно, она устарела, надо проверить свежие версии, не исправлена ли там ошибка.

Пока обновления нужно проверять и выполнять вручную, но уже начиная с 7.1 приложение iikoFront научится обновляться само, а с 7.2 оно будет автоматически обновлять плагины. Stay tuned :sunglasses:
