### ISSUE TITLE
Получение GetConceptions()

### ISSUE THREAD

**Issue by jurijshevtsov** [iiko/front.api.sdk#114]
При попытке вызова var conceptions = PluginContext.Operations.GetConceptions();
получаю ошибку
`System.ArgumentOutOfRangeException: Interface not registered
Имя параметра: entityInterfaceType
Фактическое значение было Resto.CashServer.Services.Data.IConception.

Server stack trace: 
   at Resto.CashServer.EntitiesManager.RootEntitiesManager`3.GetEntityType(Type entityInterfaceType) in J:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\EntityManager\EntitiesManager.RootEntitiesManager.cs:line 166
   at Resto.CashServer.EntitiesManager.RootEntitiesManager`3.GetAll[T](Func`2 filter) in J:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\EntityManager\EntitiesManager.RootEntitiesManager.cs:line 328
   at Resto.Front.Api.V6.OperationService.GetConceptions() in J:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Operations.g.cs:line 1464
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationService.GetConceptions()
   в Resto.Front.Api.testMonoPayment.MainForm.AddAndProcessExternalPrepay() в C:\2\Resto.Front.Api.testMonoPayment1\Resto.Front.Api.testMonoPayment\PaymentEditorTester.cs:строка 321
   в Resto.Front.Api.testMonoPayment.MainForm.<>c__DisplayClass6_0.<AddButton>b__0(Object s, EventArgs e) в C:\2\Resto.Front.Api.testMonoPayment1\Resto.Front.Api.testMonoPayment\PaymentEditorTester.cs:строка 156`

Не могу понять почему я не могу получить список концепций.
Может список концепций можно получить както по другому?

**Comment by vcpp** [comment]
А зачем вам список концепций, что вы планировали с ними делать?

Концепция — свойство точки продаж. Можно получить список точек продаж ([`GetHostTerminalPointsOfSale`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_GetHostTerminalPointsOfSale.htm)) и для каждой точки продаж узнать её концепцию ([`IPointOfSale.Conception`](https://iiko.github.io/front.api.sdk/v6/html/P_Resto_Front_Api_Data_Organization_IPointOfSale_Conception.htm)).

**Comment by vcpp** [comment]
Падение — безусловно, баг, но вопрос в том, стоит ли рассматривать концепции как самостоятельный справочник, имеют ли они смысл вне точек продаж. На первый взгляд, вызываемый вами метод правильнее удалить, чем чинить. Ну, и seealso-коммент добавить не помешает, чтобы было легче найти, с чем эти концепции используются.

**Comment by vcpp** [comment]
Похоже, этот метод никому не нужен.
Поскольку он все равно не работает, удалим его начиная с V7Preview5.

Если когда-нибудь где-нибудь понадобится справочник концепций, добавим обратно в работающем виде.
