### ISSUE TITLE
Использование метода GetConceptions()

### ISSUE THREAD

**Issue by jurijshevtsov** [iiko/front.api.sdk#115]
Добрый день.
Нужна консультация по использованию метода GetConceptions()
Я взял Ваш тестовый пример SamplePaymentPlugin в методе  AddAndProcessExternalPrepay() добавил получение Концепций 
var Conceptions = PluginContext.Operations.GetConceptions();

Но в дэбаге в этой строчке падает ошибка приведенная ниже. Как правильно получить список концепций?
Текст ошибки

`System.ArgumentOutOfRangeException: Interface not registered
Имя параметра: entityInterfaceType
Фактическое значение было Resto.CashServer.Services.Data.IConception.
Server stack trace: 
   at Resto.CashServer.EntitiesManager.RootEntitiesManager`3.GetEntityType(Type entityInterfaceType) in J:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\EntityManager\EntitiesManager.RootEntitiesManager.cs:line 166
   at Resto.CashServer.EntitiesManager.RootEntitiesManager`3.GetAll[T](Func`2 filter) in J:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\EntityManager\EntitiesManager.RootEntitiesManager.cs:line 328
   at Resto.Front.Api.V6.OperationService.GetConceptions() in J:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Operations.g.cs:line 1464
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.IOperationService.GetConceptions()
   в Resto.Front.Api.SamplePaymentPlugin.PaymentEditorTester.AddAndProcessExternalPrepay() в C:\5\front.api.sdk-master\sample\v6\Resto.Front.Api.SamplePaymentPlugin\PaymentEditorTester.cs:строка 264
   в Resto.Front.Api.SamplePaymentPlugin.PaymentEditorTester.<>c__DisplayClass5_0.<AddButton>b__0(Object s, RoutedEventArgs e) в C:\5\front.api.sdk-master\sample\v6\Resto.Front.Api.SamplePaymentPlugin\PaymentEditorTester.cs:строка 106`

**Comment by vcpp** [comment]
Duplicates #114.
