### ISSUE TITLE
Падения плагина iikoFront

### ISSUE THREAD

**Issue by Lexx8000** [iiko/front.api.sdk#15]
Добрый день!
Пишет разработчик SmartOrder. Столкнулись с проблемой падения плагина у некоторых клиентов. Проявляется в моменты большой нагрузки ресторана, т.е. когда осуществляется активная работа с плагином. Сообщений в логе cash-server нет, у плагина лог заканчивается так:

[2019-03-20 12:21:23,468] ERROR [31] - UnhandledException in plugin domain:
System.Runtime.Remoting.RemotingException: Requested Service not found
...
[2019-03-20 12:21:23,499] ERROR [31] - UnhandledException in host domain:
System.Runtime.Remoting.RemotingException: Requested Service not found
...

Каталог логов прилагаю.
[Logs.zip](https://github.com/iiko/front.api.sdk/files/3012203/Logs.zip)
Лог plugin-iikoOrderServ.log.2019-03-20

Пожалуйста, помогите идентифицировать причину вылета плагина.

**Comment by ierof** [comment]
Версия iiko 5.5.2007.0
Версия API V5
Полный текст исключения:
```[2019-03-20 12:21:23,468] ERROR [31] - UnhandledException in plugin domain:
System.Runtime.Remoting.RemotingException: Requested Service not found

Server stack trace: 
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.IDisposable.Dispose()
   at Resto.Front.Api.V5.Extensions.NotificationServiceExtensions.DisposableSubscription.Dispose() in i:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api.V5\Extensions\NotificationServiceExtensions.cs:line 201
   at Rb3PVneefkL3rsxmc7.cpA1IqnFu6NNEf0GUs.<>c.<NewOrder23>b__35_5()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
И происходит это из метода `Resto.Front.Api.V5.Extensions.NotificationServiceExtensions.DisposableSubscription.Dispose()`
 => по какой-то причине в это время iikoFront решил выключить плагин. Смотрим в лог `cash-server.log.2019-03-20` в это время. 
Но там нет выключения фронта, зато есть 
```
[2019-03-20 12:21:51,532] DEBUG [ 5] [PluginHostingService:OnHostProcessExited] - Process 3068 (“iikoOrderServ”) exited with code -532462766
[2019-03-20 12:21:51,564] DEBUG [ 5] [PluginHostingService:RemoveConnection] - Plugin “iikoOrderServ” disconnected.
```

Т.е. судя по картине логах сначала падает плагин на вызове API-метода DisposableSubscription.Dispose(). А из-за того, что случает не необработанное исключение, закрывается процесс вашего плагина. 
Я так понимаю, ваш код обсусцирован, потому что по полному стэку могу рекомендовать вам ловить исключения в методе `at Rb3PVneefkL3rsxmc7.cpA1IqnFu6NNEf0GUs.<>c.<NewOrder23>b__35_5()`. А мы пока попробуем предположить, какие действия могут вызвать такое падение в `Resto.Front.Api.V5.Extensions.NotificationServiceExtensions.DisposableSubscription.Dispose()`

**Comment by Lexx8000** [comment]
Падения в разных методах плагина происходят. Не только в NewOrder23.

**Comment by ierof** [comment]
1. Если посмотреть ещё какие-нибудь случаи воспроизведения проблемы, там те же методы нашего API фигурируют? `Resto.Front.Api.V5.Extensions.NotificationServiceExtensions.DisposableSubscription.Dispose()`
2. Если посмотреть ваши методы, в которых происходят падения, есть там обращения к одинаковым функциям нашего API?

**Comment by Lexx8000** [comment]
нет

**Comment by Lexx8000** [comment]
хотя это еще на версии V4, плагин недавно перевели на V5. Установим версию без обфускации - отправлю логи в течение пары дней.

**Comment by vcpp** [comment]
А нет ли случаев воспроизведения на 6.2+? У нас там побольше логирования.

**Comment by Lexx8000** [comment]
нет, 4 случая с версиями 5.5.2007.0, 5.5.3025.0, 5.5.4014.0

**Comment by Lexx8000** [comment]
Нашел в методе NewOrder23 вызов subscription?.Dispose() в случае, если после ожидания в три секунды не создался наш внутренний xml нового заказа, не могу точно вспомнить зачем - это было сделано давно и так нормально работало - скорей всего это было признаком завершения работы плагина. А в периоды большой нагрузки плагин не успевает обрабатывать заказы. Попробую добавить условий проверки и время ожидания. 
Пока отложите свои проверки, передам плагин на тест.

**Comment by Lexx8000** [comment]
Плагин проработал неделю, в том же месте вылетов не было. Но вылетел в момент переподписки на события - плагин делает Dispose и новую подписку в момент открытия смены, сделано для тех, кто не выключает фронт, на предыдущих версиях iiko были проблемы с подпиской при открытии-закрытии смены. Похоже сейчас нужно делать Dispose только при остановке плагина. Какие у Вас рекомендации по подписке на события?

**Comment by vcpp** [comment]
> Установим версию без обфускации - отправлю логи в течение пары дней.

Где их можно посмотреть? Вообще хотелось бы посмотреть комплект логов + код плагина.
Можете отправить через техподдержку, если не хотите публиковать в открытом доступе.

**Comment by Lexx8000** [comment]
Падения устранились, метод Dispose создавал исключение, которое не обрабатывает фронт. Спасибо, задачу можно закрыть.
