### ISSUE TITLE
ФР постоянно отваливается с ошибкой (V7Preview4) 

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#208]
Доброй ночи
 ФР периодически отваливается с ошибками, что он не найден
``` log
[2021-01-30 01:12:03,929] ERROR [103] [DevicesService:ExecuteWithResult:789] - Resto.Front.Api.Exceptions.DeviceException: Geri qaytarma əməliyyatı dayandırıldı .

Server stack trace: 
   в Resto.Front.Api.AZN.TokenCR.eKassa.EKassa.DoChequeRefundAndCancel(ChequeTask chequeTask, IViewManager viewManager, String reportName, EnumCreateDocumentCommand enumCreateDocumentCommand)
   в Resto.Front.Api.AZN.TokenCR.eKassa.EKassa.DoCheque(ChequeTask chequeTask, IViewManager viewManager)
   в Resto.Front.Api.AZN.TokenCR.EKassaCashRegister.DoCheque(ChequeTask chequeTask, IViewManager viewManager)
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.Devices.ICashRegister.DoCheque(ChequeTask chequeTask, IViewManager viewManager)
   at Resto.Front.Api.V7Preview4.Device.CashRegisterWrapper.<>c__DisplayClass3_1.<DoCheque>b__0() in L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview4\Device\CashRegisterWrapper.cs:line 43
   at Resto.Front.Api.V7Preview4.Device.CashRegisterWrapper.<>c__DisplayClass21_0`1.<SafeExecute>b__0() in L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview4\Device\CashRegisterWrapper.cs:line 201
   at Resto.Front.Api.V7Preview4.Device.DeviceWrapper.WrapExpectedExceptions[T](Func`1 func) in L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview4\Device\DeviceWrapper.cs:line 71
   at Resto.Front.Api.V7Preview4.Device.CashRegisterWrapper.DoCheque(ChequeTask chequeTask) in L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview4\Device\CashRegisterWrapper.cs:line 0
   at Resto.Front.Api.Devices.DevicesService.ExecuteWithResult(String requestId, String taskName, Guid deviceId, Func`2 action, Boolean skipAutorun) in L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\Devices\DevicesService.cs:line 789
```
или
``` log

2021-01-30 00:15:55,547] ERROR [79] [CafeSession:PrintZReport:348] - Can't print ZReport: Устройство с заданным идентификатором не найдено
[2021-01-30 00:15:55,553] ERROR [79] [CafeSessionService:CloseActiveCafeSession:224] - Error on cash register: Устройство с заданным идентификатором не найдено
[2021-01-30 00:15:55,556] ERROR [ 1] [CafeSessionController+StepBase:ShowError:136] - Error on step StepCloseSession
Resto.Framework.Common.RestoException: Устройство с заданным идентификатором не найдено

Server stack trace: 
   в Resto.Front.Controllers.CloseCafeSessionController.StepCloseSessionBase.ZReport(XElement zReportMarkup) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\CloseCafeSessionController.StepCloseSessionBase.cs:строка 148
   в Resto.Front.Controllers.CloseCafeSessionController.StepCloseSession.DoCompleteActions(XElement zReportMarkup) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\CloseCafeSessionController.StepCloseSession.cs:строка 124
   в Resto.Front.Controllers.CloseCafeSessionController.StepCloseSessionBase.<>c__DisplayClass16_0.<Complete>b__0() в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\CloseCafeSessionController.StepCloseSessionBase.cs:строка 103
   в Resto.Front.Main.MVC.ViewManager.<>c__DisplayClass57_0.<ExecuteWithProgressBar>b__0() в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.ProgressBar.cs:строка 25
   в System.Threading.Tasks.Task`1.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

Exception rethrown at [0]: 
   в Resto.Front.Main.MVC.States.ProgressBarState`1.ConvertResult(Object result) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\States\ProgressBarState.cs:строка 67
   в Resto.Front.Main.MVC.ViewManager.ShowProgressBarCore[TResult](ProgressBarState`1 state) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.Popups.cs:строка 161
   в Resto.Front.Main.MVC.ViewManager.ShowProgressBarWithResult[TResult](ProgressBarState`1 state) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.Popups.cs:строка 111
   в Resto.Front.Main.MVC.ViewManager.ExecuteWithProgressBar[TResult](Task`1 task, String message, IObservable`1 messages, Boolean canShowAtShutdown) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.ProgressBar.cs:строка 76
   в Resto.Front.Main.MVC.ViewManager.ExecuteWithProgressBar[TResult](Func`1 func, String message, IObservable`1 messages, Boolean canShowAtShutdown) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.ProgressBar.cs:строка 37
   в Resto.Front.Main.MVC.ViewManager.ExecuteWithProgressBar(Action action, String message, IObservable`1 messages, Boolean canShowAtShutdown) в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Main\MVC\ViewManager.ProgressBar.cs:строка 25
   в Resto.Front.Controllers.CloseCafeSessionController.StepCloseSessionBase.Complete() в L:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Controllers\CloseCafeSessionController.StepCloseSessionBase.cs:строка 91
```

**Comment by igorpooh1978** [comment]
в cashserver.log
``` log
[2021-01-30 01:59:56,106]  INFO [57] [CashRegisterService:AskIfToRepeatOperation] - Error on cash register Внешний фискальный регистратор. Try to repeat operation: True
[2021-01-30 01:59:56,110]  INFO [57] [CashRegisterService:ExecuteSerialOperation] - Begin serial operation on CashRegister 6147ca24-d0ee-4676-8a84-2bd884b57343.
[2021-01-30 01:59:56,110] DEBUG [57] [AgentWrapper:PutTaskInternal] - Send agent request: <BuildCashResultTask cls="BuildCashResultTask"><id>49e010f2-81bb-47c8-b278-2e274e43f0b3</id><deviceId>6147ca24-d0ee-4676-8a84-2bd884b57343</deviceId><success>true</success></BuildCashResultTask>
[2021-01-30 01:59:56,123] DEBUG [ 7] [AgentWrapper:OnAgentResponse] - Receive agent callback: <?xml version="1.0"?>
<root cls="AgentErrorResult"><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><details>{$NoDetails}</details><hrCode>0</hrCode><localTime>1611957596</localTime><message>{$ErrorDeviceNotFound}</message><nCode>-113</nCode><name>DESKTOP-Q3QTEFO</name><success>false</success><taskId>49E010F2-81BB-47C8-B278-2E274E43F0B3</taskId></root>

[2021-01-30 01:59:56,124] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Remove agent task from queue
[2021-01-30 01:59:56,124] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Begin invoke callback delegate..
[2021-01-30 01:59:56,124] DEBUG [57] [AgentWrapper:PutTaskInternal] - Send agent request: <GetDeviceListTask cls="GetDeviceListTask"><id>86f101a0-2375-4505-8010-0d5c94811c55</id><deviceId>11111111-0000-0000-0000-000000000001</deviceId><success>true</success></GetDeviceListTask>
[2021-01-30 01:59:56,129] DEBUG [ 7] [AgentWrapper:OnAgentResponse] - Receive agent callback: <?xml version="1.0"?>
<root cls="AgentInfo"><agentDevices/><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><localTime>1611957596</localTime><message></message><name>DESKTOP-Q3QTEFO</name><success>true</success><taskId>86F101A0-2375-4505-8010-0D5C94811C55</taskId><warnings>false</warnings></root>

[2021-01-30 01:59:56,129] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Remove agent task from queue
[2021-01-30 01:59:56,130] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Begin invoke callback delegate..
[2021-01-30 01:59:56,130]  INFO [57] [CashRegisterService:CheckSerialNumber] - Execute operation failed. CR serial , but expected all.
[2021-01-30 01:59:56,130]  INFO [57] [CashRegisterService:EndSerialOperation] - End serial operation on CashRegister 6147ca24-d0ee-4676-8a84-2bd884b57343.
[2021-01-30 02:00:09,573]  INFO [57] [CashRegisterService:AskIfToRepeatOperation] - Error on cash register Внешний фискальный регистратор. Try to repeat operation: True
[2021-01-30 02:00:09,573]  INFO [57] [CashRegisterService:ExecuteSerialOperation] - Begin serial operation on CashRegister 6147ca24-d0ee-4676-8a84-2bd884b57343.
[2021-01-30 02:00:09,574] DEBUG [57] [AgentWrapper:PutTaskInternal] - Send agent request: <BuildCashResultTask cls="BuildCashResultTask"><id>371142e8-95b3-41b0-8c9c-8875ceee5465</id><deviceId>6147ca24-d0ee-4676-8a84-2bd884b57343</deviceId><success>true</success></BuildCashResultTask>
[2021-01-30 02:00:09,587] DEBUG [ 7] [AgentWrapper:OnAgentResponse] - Receive agent callback: <?xml version="1.0"?>
<root cls="AgentErrorResult"><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><details>{$NoDetails}</details><hrCode>0</hrCode><localTime>1611957609</localTime><message>{$ErrorDeviceNotFound}</message><nCode>-113</nCode><name>DESKTOP-Q3QTEFO</name><success>false</success><taskId>371142E8-95B3-41B0-8C9C-8875CEEE5465</taskId></root>

[2021-01-30 02:00:09,588] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Remove agent task from queue
[2021-01-30 02:00:09,588] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Begin invoke callback delegate..
[2021-01-30 02:00:09,588] DEBUG [57] [AgentWrapper:PutTaskInternal] - Send agent request: <GetDeviceListTask cls="GetDeviceListTask"><id>7be3c0c7-70d2-46c7-a8c4-7d859248c90b</id><deviceId>11111111-0000-0000-0000-000000000001</deviceId><success>true</success></GetDeviceListTask>
[2021-01-30 02:00:09,593] DEBUG [ 7] [AgentWrapper:OnAgentResponse] - Receive agent callback: <?xml version="1.0"?>
<root cls="AgentInfo"><agentDevices/><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><localTime>1611957609</localTime><message></message><name>DESKTOP-Q3QTEFO</name><success>true</success><taskId>7BE3C0C7-70D2-46C7-A8C4-7D859248C90B</taskId><warnings>false</warnings></root>

[2021-01-30 02:00:09,593] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Remove agent task from queue
[2021-01-30 02:00:09,593] DEBUG [ 7] [AgentWrapper:TaskInvokeWithResult] - Begin invoke callback delegate..
[2021-01-30 02:00:09,594]  INFO [57] [CashRegisterService:CheckSerialNumber] - Execute operation failed. CR serial , but expected all.
[2021-01-30 02:00:09,594]  INFO [57] [CashRegisterService:EndSerialOperation] - End serial operation on CashRegister 6147ca24-d0ee-4676-8a84-2bd884b57343.

```

**Comment by igorpooh1978** [comment]
device.log
``` log
[30.01.2021 02:04:37,673] [INFO-7752] New message '10976394-3244-48AC-A74E-5FBA3676ED54' for device '6147CA24-D0EE-4676-8A84-2BD884B57343' from '<local>' (agent.cpp:467)
[30.01.2021 02:04:37,673] [ERROR-7752] Runtime error -113: {$ErrorDeviceNotFound} (agent.cpp:478)
[30.01.2021 02:04:37,716] [INFO-7752] New message 'FC369D54-5AB6-486B-B02D-F04564DA9676' for device '6147CA24-D0EE-4676-8A84-2BD884B57343' from '<local>' (agent.cpp:467)
[30.01.2021 02:04:37,716] [ERROR-7752] Runtime error -113: {$ErrorDeviceNotFound} (agent.cpp:478)
[30.01.2021 02:04:37,725] [INFO-7752] New message '5862CD64-6F2C-4C56-B16A-20F45FB38AE4' for device '11111111-0000-0000-0000-000000000001' from '<local>' (agent.cpp:467)
[30.01.2021 02:04:37,725] [INFO-7752] iikoAgent is processing device list command (agent.cpp:585)
```

agent.log
``` log

[2021-01-30 02:04:37,715] DEBUG [52] [AgentHost:PutAgentRequest] - <BuildCashResultTask cls="BuildCashResultTask"><id>fc369d54-5ab6-486b-b02d-f04564da9676</id><deviceId>6147ca24-d0ee-4676-8a84-2bd884b57343</deviceId><success>true</success></BuildCashResultTask>
[2021-01-30 02:04:37,718] DEBUG [52] [AgentHost:OnResponse] - <?xml version="1.0"?>
<root cls="AgentErrorResult"><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><details>{$NoDetails}</details><hrCode>0</hrCode><localTime>1611957877</localTime><message>{$ErrorDeviceNotFound}</message><nCode>-113</nCode><name>DESKTOP-Q3QTEFO</name><success>false</success><taskId>FC369D54-5AB6-486B-B02D-F04564DA9676</taskId></root>

[2021-01-30 02:04:37,724] DEBUG [52] [AgentHost:PutAgentRequest] - <GetDeviceListTask cls="GetDeviceListTask"><id>5862cd64-6f2c-4c56-b16a-20f45fb38ae4</id><deviceId>11111111-0000-0000-0000-000000000001</deviceId><success>true</success></GetDeviceListTask>
[2021-01-30 02:04:37,726] DEBUG [52] [AgentHost:OnResponse] - <?xml version="1.0"?>
<root cls="AgentInfo"><agentDevices/><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><localTime>1611957877</localTime><message></message><name>DESKTOP-Q3QTEFO</name><success>true</success><taskId>5862CD64-6F2C-4C56-B16A-20F45FB38AE4</taskId><warnings>false</warnings></root>
```

prelimenaryorder
``` log

[2021-01-30 02:04:37,715] DEBUG [52] [AgentHost:PutAgentRequest] - <BuildCashResultTask cls="BuildCashResultTask"><id>fc369d54-5ab6-486b-b02d-f04564da9676</id><deviceId>6147ca24-d0ee-4676-8a84-2bd884b57343</deviceId><success>true</success></BuildCashResultTask>
[2021-01-30 02:04:37,718] DEBUG [52] [AgentHost:OnResponse] - <?xml version="1.0"?>
<root cls="AgentErrorResult"><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><details>{$NoDetails}</details><hrCode>0</hrCode><localTime>1611957877</localTime><message>{$ErrorDeviceNotFound}</message><nCode>-113</nCode><name>DESKTOP-Q3QTEFO</name><success>false</success><taskId>FC369D54-5AB6-486B-B02D-F04564DA9676</taskId></root>

[2021-01-30 02:04:37,724] DEBUG [52] [AgentHost:PutAgentRequest] - <GetDeviceListTask cls="GetDeviceListTask"><id>5862cd64-6f2c-4c56-b16a-20f45fb38ae4</id><deviceId>11111111-0000-0000-0000-000000000001</deviceId><success>true</success></GetDeviceListTask>
[2021-01-30 02:04:37,726] DEBUG [52] [AgentHost:OnResponse] - <?xml version="1.0"?>
<root cls="AgentInfo"><agentDevices/><agentId>163DF354-A7A3-4173-A941-09DE392B0BEC</agentId><localTime>1611957877</localTime><message></message><name>DESKTOP-Q3QTEFO</name><success>true</success><taskId>5862CD64-6F2C-4C56-B16A-20F45FB38AE4</taskId><warnings>false</warnings></root>

```

**Comment by letolica** [comment]
Класс, реализующий интерфейс `ICashRegisterFactory` и наследующийся от MBR-объекта, должен переопределять метод
```
// Note http://msdn.microsoft.com/en-us/library/23bk23zc(v=vs.100).aspx
public override object InitializeLifetimeService() { return null; }
```

**Comment by igorpooh1978** [comment]
В том то вся и штука, что он стоит
![image](https://user-images.githubusercontent.com/47010778/106433912-e32f0380-6481-11eb-8181-469c5ffeea9f.png)

но не переопределяет (.
Вылечилось путем перехода на V7Pr5

**Comment by letolica** [comment]
В V7Preview5 классу, реализующему {{ICashRegisterFactory}}, нет необходимости наследоваться от MBR-объекта и переопределять {{InitializeLifetimeService}}, этот код был перенесен внутрь фронта. На это к сожалению пока нет заметки в документации.

**Comment by letolica** [comment]
Кстати, класс, реализующий `Devices.ICashRegister` в V7Preview4 тоже должен наследоваться от MBR-объекта и переопределять `InitializeLifetimeService`. К сожалению, без полного комплекта логов и исходников плагина сложно сказать, в чём именно у Вас была ошибка.

**Comment by igorpooh1978** [comment]
Согласен, без кода ни как
В любом случае историю с lifetime я обычно указываю везде, т.к. брал ваши примеры
``` c#
    internal sealed class EKassaCashRegister : MarshalByRefObject, Devices.ICashRegister
    {

        // Note http://msdn.microsoft.com/en-us/library/23bk23zc(v=vs.100).aspx
        public override object InitializeLifetimeService()
        {
            return null;
        }
```
и этот кусок таскается из плагина в плагин
