### ISSUE TITLE
Запуск RabbitMQ клиента для iikoFront клиента

### ISSUE THREAD

**Issue by igorpooh1978** [iiko/front.api.sdk#250]
Всем привет

Подскажите пожалуйста. Как запустить RabbitMQ клиента в плагине.
Делаю тестовое приложение (консоль)
```
var factory = new ConnectionFactory
            {
                UseBackgroundThreadsForIO = true,
                HostName = "127.0.0.1",
                HandshakeContinuationTimeout = new TimeSpan(0, 0, 50),
                ContinuationTimeout = new TimeSpan(0, 0, 50),
                 RequestedConnectionTimeout = new TimeSpan(0, 0, 50),
                  SocketReadTimeout = new TimeSpan(0, 0, 50),
                  SocketWriteTimeout = new TimeSpan(0, 0, 50)
            };
            //factory.Uri = new Uri(connectionString);
            using (var connection = factory.CreateConnection())
            using (var channel = connection.CreateModel())
            {
                channel.QueueDeclare(queue: "messages1",
                                     durable: false,
                                     exclusive: false,
                                     autoDelete: false,
                                     arguments: null);

                var consumer = new EventingBasicConsumer(channel);

                consumer.Received += (sender, e) =>
                {
                    var body = e.Body;
                    var message = Encoding.UTF8.GetString(body.ToArray());
                    PluginContext.Log.Info($" Received message: {message}");
                };

                channel.BasicConsume(queue: "messages1",
                                     autoAck: true,
                                     consumer: consumer);

                PluginContext.Log.Info("Subscribed to the queue 'messages1'");


            }
```

Запускаю приложение в логе RabbitMQ
```
2021-07-28 21:13:56.112000+03:00 [info] <0.1745.0> Supervisor {<0.1745.0>,rabbit_connection_sup}: child helper_sup started (<0.1746.0>): {rabbit_connection_helper_sup,start_link,[]}
2021-07-28 21:13:56.112000+03:00 [info] <0.1745.0> Supervisor {<0.1745.0>,rabbit_connection_sup}: child reader started (<0.1747.0>): {rabbit_reader,start_link,[<0.1746.0>,{acceptor,{0,0,0,0,0,0,0,0},5672}]}
2021-07-28 21:13:56.127000+03:00 [info] <0.1747.0> accepting AMQP connection <0.1747.0> ([::1]:62723 -> [::1]:5672)
2021-07-28 21:13:56.166000+03:00 [debug] <0.1747.0> Raw client connection hostname during authN phase: {0,0,0,0,0,0,0,1}
2021-07-28 21:13:56.166000+03:00 [debug] <0.1747.0> Resolved client hostname during authN phase: ::1
2021-07-28 21:13:56.166000+03:00 [debug] <0.1747.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2021-07-28 21:13:56.173000+03:00 [info] <0.1746.0> Supervisor {<0.1746.0>,rabbit_connection_helper_sup}: child collector started (<0.1749.0>): {rabbit_queue_collector,start_link,[<<"[::1]:62723 -> [::1]:5672">>]}
2021-07-28 21:13:56.173000+03:00 [info] <0.1746.0> Supervisor {<0.1746.0>,rabbit_connection_helper_sup}: child heartbeat_sender started (<0.1750.0>): {rabbit_heartbeat,start_heartbeat_sender,[#Port<0.597>,60,#Fun<rabbit_reader.4.103937772>,{heartbeat_sender,<<"[::1]:62723 -> [::1]:5672">>}]}
2021-07-28 21:13:56.173000+03:00 [info] <0.1746.0> Supervisor {<0.1746.0>,rabbit_connection_helper_sup}: child heartbeat_receiver started (<0.1751.0>): {rabbit_heartbeat,start_heartbeat_receiver,[#Port<0.597>,60,#Fun<rabbit_reader.5.103937772>,{heartbeat_receiver,<<"[::1]:62723 -> [::1]:5672">>}]}
2021-07-28 21:13:56.174000+03:00 [info] <0.1746.0> Supervisor {<0.1746.0>,rabbit_connection_helper_sup}: child channel_sup_sup started (<0.1752.0>): {rabbit_channel_sup_sup,start_link,[]}
2021-07-28 21:13:56.174000+03:00 [info] <0.1747.0> connection <0.1747.0> ([::1]:62723 -> [::1]:5672): user 'guest' authenticated and granted access to vhost '/'
2021-07-28 21:13:56.179000+03:00 [info] <0.1754.0> Supervisor {<0.1754.0>,rabbit_channel_sup}: child writer started (<0.1755.0>): {rabbit_writer,start_link,[#Port<0.597>,1,131072,rabbit_framing_amqp_0_9_1,<0.1747.0>,{<<"[::1]:62723 -> [::1]:5672">>,1},true]}
2021-07-28 21:13:56.179000+03:00 [info] <0.1754.0> Supervisor {<0.1754.0>,rabbit_channel_sup}: child limiter started (<0.1756.0>): {rabbit_limiter,start_link,[{<<"[::1]:62723 -> [::1]:5672">>,1}]}
2021-07-28 21:13:56.179000+03:00 [info] <0.1754.0> Supervisor {<0.1754.0>,rabbit_channel_sup}: child channel started (<0.1757.0>): {rabbit_channel,start_link,[1,<0.1747.0>,<0.1755.0>,<0.1747.0>,<<"[::1]:62723 -> [::1]:5672">>,rabbit_framing_amqp_0_9_1,{user,<<"guest">>,[administrator],[{rabbit_auth_backend_internal,none}]},<<"/">>,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"authentication_failure_close">>,bool,true}],<0.1749.0>,<0.1756.0>]}
2021-07-28 21:13:56.200000+03:00 [info] <0.1747.0> closing AMQP connection <0.1747.0> ([::1]:62723 -> [::1]:5672, vhost: '/', user: 'guest')
2021-07-28 21:13:56.201000+03:00 [debug] <0.1762.0> Closing all channels from connection '[::1]:62723 -> [::1]:5672' because it has been closed
2021-07-28 21:13:57.923000+03:00 [info] <0.1764.0> Supervisor {<0.1764.0>,rabbit_connection_sup}: child helper_sup started (<0.1765.0>): {rabbit_connection_helper_sup,start_link,[]}
2021-07-28 21:13:57.923000+03:00 [info] <0.1764.0> Supervisor {<0.1764.0>,rabbit_connection_sup}: child reader started (<0.1766.0>): {rabbit_reader,start_link,[<0.1765.0>,{acceptor,{0,0,0,0,0,0,0,0},5672}]}
2021-07-28 21:13:57.923000+03:00 [info] <0.1766.0> accepting AMQP connection <0.1766.0> ([::1]:62728 -> [::1]:5672)
2021-07-28 21:13:57.926000+03:00 [debug] <0.1766.0> Raw client connection hostname during authN phase: {0,0,0,0,0,0,0,1}
2021-07-28 21:13:57.926000+03:00 [debug] <0.1766.0> Resolved client hostname during authN phase: ::1
2021-07-28 21:13:57.926000+03:00 [debug] <0.1766.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2021-07-28 21:13:57.929000+03:00 [info] <0.1765.0> Supervisor {<0.1765.0>,rabbit_connection_helper_sup}: child collector started (<0.1767.0>): {rabbit_queue_collector,start_link,[<<"[::1]:62728 -> [::1]:5672">>]}
2021-07-28 21:13:57.929000+03:00 [info] <0.1765.0> Supervisor {<0.1765.0>,rabbit_connection_helper_sup}: child heartbeat_sender started (<0.1768.0>): {rabbit_heartbeat,start_heartbeat_sender,[#Port<0.599>,60,#Fun<rabbit_reader.4.103937772>,{heartbeat_sender,<<"[::1]:62728 -> [::1]:5672">>}]}
2021-07-28 21:13:57.929000+03:00 [info] <0.1765.0> Supervisor {<0.1765.0>,rabbit_connection_helper_sup}: child heartbeat_receiver started (<0.1769.0>): {rabbit_heartbeat,start_heartbeat_receiver,[#Port<0.599>,60,#Fun<rabbit_reader.5.103937772>,{heartbeat_receiver,<<"[::1]:62728 -> [::1]:5672">>}]}
2021-07-28 21:13:57.929000+03:00 [info] <0.1765.0> Supervisor {<0.1765.0>,rabbit_connection_helper_sup}: child channel_sup_sup started (<0.1770.0>): {rabbit_channel_sup_sup,start_link,[]}
2021-07-28 21:13:57.929000+03:00 [info] <0.1766.0> connection <0.1766.0> ([::1]:62728 -> [::1]:5672): user 'guest' authenticated and granted access to vhost '/'
2021-07-28 21:13:57.930000+03:00 [info] <0.1772.0> Supervisor {<0.1772.0>,rabbit_channel_sup}: child writer started (<0.1773.0>): {rabbit_writer,start_link,[#Port<0.599>,1,131072,rabbit_framing_amqp_0_9_1,<0.1766.0>,{<<"[::1]:62728 -> [::1]:5672">>,1},true]}
2021-07-28 21:13:57.930000+03:00 [info] <0.1772.0> Supervisor {<0.1772.0>,rabbit_channel_sup}: child limiter started (<0.1774.0>): {rabbit_limiter,start_link,[{<<"[::1]:62728 -> [::1]:5672">>,1}]}
2021-07-28 21:13:57.930000+03:00 [info] <0.1772.0> Supervisor {<0.1772.0>,rabbit_channel_sup}: child channel started (<0.1775.0>): {rabbit_channel,start_link,[1,<0.1766.0>,<0.1773.0>,<0.1766.0>,<<"[::1]:62728 -> [::1]:5672">>,rabbit_framing_amqp_0_9_1,{user,<<"guest">>,[administrator],[{rabbit_auth_backend_internal,none}]},<<"/">>,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"authentication_failure_close">>,bool,true}],<0.1767.0>,<0.1774.0>]}
2021-07-28 21:13:57.932000+03:00 [info] <0.1766.0> closing AMQP connection <0.1766.0> ([::1]:62728 -> [::1]:5672, vhost: '/', user: 'guest')
2021-07-28 21:13:57.932000+03:00 [debug] <0.1780.0> Closing all channels from connection '[::1]:62728 -> [::1]:5672' because it has been closed

```

Теперь тоже самое для плагина
В логе RabbitMQ следующее
```
2021-07-28 21:08:41.938000+03:00 [debug] <0.1517.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2021-07-28 21:08:47.854000+03:00 [info] <0.1524.0> Supervisor {<0.1524.0>,rabbit_connection_sup}: child helper_sup started (<0.1525.0>): {rabbit_connection_helper_sup,start_link,[]}
2021-07-28 21:08:47.854000+03:00 [info] <0.1524.0> Supervisor {<0.1524.0>,rabbit_connection_sup}: child reader started (<0.1526.0>): {rabbit_reader,start_link,[<0.1525.0>,{acceptor,{0,0,0,0},5672}]}
2021-07-28 21:08:47.872000+03:00 [info] <0.1526.0> accepting AMQP connection <0.1526.0> (127.0.0.1:52454 -> 127.0.0.1:5672)
2021-07-28 21:08:57.861000+03:00 [error] <0.1526.0> closing AMQP connection <0.1526.0> (127.0.0.1:52454 -> 127.0.0.1:5672):
2021-07-28 21:08:57.861000+03:00 [error] <0.1526.0> {handshake_timeout,frame_header}
2021-07-28 21:08:57.863000+03:00 [debug] <0.1534.0> Closing all channels from connection '127.0.0.1:52454 -> 127.0.0.1:5672' because it has been closed
2021-07-28 21:09:42.263000+03:00 [debug] <0.1562.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2021-07-28 21:10:41.957000+03:00 [debug] <0.1600.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
2021-07-28 21:11:42.281000+03:00 [debug] <0.1640.0> User 'guest' authenticated successfully by backend rabbit_auth_backend_internal
```

![image](https://user-images.githubusercontent.com/47010778/127374298-bb61da1f-f92d-4d55-a4f2-68d57083bf2b.png)
1. PossibleAuthenticationFailureException: Possibly caused by authentication failure

2. OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=541, text='Unexpected Exception', classId=0, methodId=0, cause=System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.ReadByte()
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer) in /_/projects/RabbitMQ.Client/client/impl/Frame.cs:line 222
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame() in /_/projects/RabbitMQ.Client/client/impl/SocketFrameHandler.cs:line 220
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration() in /_/projects/RabbitMQ.Client/client/impl/Connection.cs:line 557
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop() in /_/projects/RabbitMQ.Client/client/impl/Connection.cs:line 499

Что происходит на iikoFront, что он не может связаться с очередью?
Пробовал также и запустить под админом и напрямую через Debug.Launch ошибка одинаковая

**Comment by vcpp** [comment]
> Как запустить RabbitMQ клиента в плагине.

— Здравствуйте, это канал об аниме?
— Да.
— Как мне пропатчить KDE2 под FreeBSD?

> `System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host`
> Что происходит на iikoFront, что он не может связаться с очередью?

При чём тут iikoFront, если в сообщении об ошибке указано, что подключение закрыто по инициативе другой стороны? Проверьте, не блокируется ли подключение для *Resto.Front.Api.Host.exe* файрволом.

В любом случае, проблемы с использованием сторонней библиотеки, в том числе трудности диагностики, лучше адресовать разработчикам этой библиотеки или сообществу пользователей этой библиотеки.
Могу только заверить, что плагины, использующие кролика и iikoFront API, существуют и вполне себе работают.

**Comment by igorpooh1978** [comment]
Собственно говоря вопрос решился скачиванием исходников с gitа
