### ISSUE TITLE
Подписка после падения не работает

### ISSUE THREAD

**Issue by Lizzzzzard** [iiko/front.api.sdk#256]
После того как подписка ловит Exception, она больше не работает, единственный способ ее восстановить это перезагрузить фронт. Есть ли способы чтобы подписка ожила без перезагрузки?
```
[2021-08-08 12:12:42,255]  WARN [10] - Exception in “BeOpen.Front.Plugins.Share” plugin's handler for “OrderEditBarcodeScanned”: System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace: 
   at BeOpen.Front.Plugins.ToshibaLoyalty.WebApiClient.Helpers.Converter.CheckBalanceResult(ApiMemberLookupResponse result) in C:\Users\zhmyl\Desktop\OpenService\Projects\ToshibaAndShare\toshiba-loyalty\BeOpen.Front.Plugins.ToshibaLoyalty\WebApiClient\Helpers\Converter.cs:line 280
   at BeOpen.Front.Plugins.ToshibaLoyalty.WebApiClient.ToshibaApiClient.ApiMemberRequest(String id) in C:\Users\zhmyl\Desktop\OpenService\Projects\ToshibaAndShare\toshiba-loyalty\BeOpen.Front.Plugins.ToshibaLoyalty\WebApiClient\ApiClient.cs:line 365
   at BeOpen.Front.Plugins.ToshibaLoyalty.ToshibaLoyaltyPlugin.OrderEditBarcodeScanned(ValueTuple`4 arg) in C:\Users\zhmyl\Desktop\OpenService\Projects\ToshibaAndShare\toshiba-loyalty\BeOpen.Front.Plugins.ToshibaLoyalty\ToshibaLoyaltyPlugin.cs:line 919
   at Resto.Front.Api.RemotingHelpers.RemotableFunc`2.Invoke(T arg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.RemotingHelpers.RemotableFunc`2.Invoke(T arg)
   at Resto.Front.Api.V7Preview5.NotificationsProvider.<>c__DisplayClass95_0.<OnOrderEditBarcodeScanned>b__0(Subscription`1 s, IOrder order, IOperationService os, IViewManager vm) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview5\NotificationsProvider.cs:line 261
   at Resto.Front.Api.V7Preview5.NotificationsProvider.<>c__DisplayClass104_0`1.<CallHandlersUntilHandled>b__0(Subscription`1 subscription) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview5\NotificationsProvider.cs:line 444
   at Resto.Front.Api.V7Preview5.NotificationsProvider.CallHandlers[THandler,TResult](ReadOptimizedConcurrentCollection`1 subscriptions, String eventName, Func`2 invoke, Func`2 filter, Func`2 stopCondition) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7Preview5\NotificationsProvider.cs:line 411
```

**Comment by vcpp** [comment]
Обработчик уведомления не должен выбрасывать исключения кроме тех, что явно предусмотрены контрактом. Например, операцию [`BeforeOrderBill`](https://iiko.github.io/front.api.sdk/v7/html/P_Resto_Front_Api_INotificationService_BeforeOrderBill.htm) можно прервать, выбросив `OperationCanceledException`, это является частью контракта, приложение iikoFront знает, как реагировать на такое исключение. Для `OrderEditBarcodeScanned` никакие исключения не ожидаются. Если в плагине баг, приводящий к `NullReferenceException` при обработке уведомления о сканировании штрихкода, надо исправить этот баг, а не искать способ его игнорировать.

Впрочем, игнорировать непредвиденные исключения несложно, это можно делать на стороне плагина, достаточно обернуть падающий обработчик в «глухой» try/catch, подавляя любые исключения. Так делать [не рекомендуется](https://intellitect.com/exceptionguidelinesforcsharp/), непредвиденные исключения на то и непредвиденные, что заранее предусмотреть какую-то осмысленную реакцию на них невозможно, последствия непредсказуемы, но это ваш плагин, ваши риски, вам решать.
