### ISSUE TITLE
Падение плагина при работе с модулем Доставки на касcе (System.Runtime.Remoting.RemotingException: Failed to write to an IPC Port: Идет закрытие канала.)

### ISSUE THREAD

**Issue by vladislav250899** [iiko/front.api.sdk#301]
Здраствуйте, коллеги!
Используем API Payment для нашего плагина для подключения внешнего бонусного типа оплаты.
По обращениям бизнесов плагин успешно работает в обычном режиме, когда покупка через тип оплаты проходит при заказе в заведении.

Если заказ осуществляется через доставку или самовывоз модуля Доставки, то при выборе внешнего типа оплаты происходит ошибка. Получили также обратную связь от бизнеса, что такая ошибка только на 1 заведении, а на другом все успешно работает.
Скрин ошибки:
![image](https://user-images.githubusercontent.com/49268908/144210272-eaad0939-55ca-4201-a7d3-fc7ba920cf97.png)

В error.log в это время видим следующее:
[2021-11-19 14:44:07,542] ERROR [79] [ApiExtensionsService:OnPaymentAdded:251] - System.Runtime.Remoting.RemotingException: Failed to write to an IPC Port: Идет закрытие канала.

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Write(Byte[] data, Int32 offset, Int32 size)
   at System.Runtime.Remoting.Channels.ChunkedMemoryStream.WriteTo(Stream stream)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.SendRequest(IMessage msg, ITransportHeaders headers, Stream contentStream)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IExternalPaymentProcessor.OnPaymentAdded(IOrder order, IPaymentItem paymentItem, IUser cashier, IOperationService operationService, IReceiptPrinter printer, IViewManager viewManager, IPaymentDataContext context)
   at Resto.Front.Api.V6.Payment.PaymentProcessorWrapper.<>c__DisplayClass7_5.<OnPaymentAdded>b__0() in M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Payment\PaymentProcessorWrapper.cs:line 91
   at Resto.Front.Api.V6.Payment.PaymentProcessorWrapper.<>c__DisplayClass17_0.<WrapExpectedExceptions>b__0() in M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Payment\PaymentProcessorWrapper.cs:line 168
   at Resto.Front.Api.V6.Payment.PaymentProcessorWrapper.WrapExpectedExceptions[T](Func`1 func) in M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Payment\PaymentProcessorWrapper.cs:line 154
   at Resto.Front.Api.V6.Payment.PaymentProcessorWrapper.WrapExpectedExceptions(Action action) in M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Payment\PaymentProcessorWrapper.cs:line 168
   at Resto.Front.Api.V6.Payment.PaymentProcessorWrapper.OnPaymentAdded(IBaseOrderEntity order, IExternalPaymentItem paymentItem, IUser cashier, ICashRegister cashRegister, Action`1 changeProgressBarMessage, ExtensionPoints extensionPoint, ILockedObjectsToken token) in M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V6\Payment\PaymentProcessorWrapper.cs:line 91
   at Resto.Front.Api.Common.ApiExtensionsService.OnPaymentAdded(IBaseOrderEntity order, ILockedObjectsToken token, IExternalPaymentItem item, String key, ICashRegister cashRegister, IUser cashier, Action`1 changeProgressBarMessage) in M:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\Common\ApiExtensionsService.cs:line 251

Просим помочь разобраться в причине возникновения ошибки и подсказать пути решения.
Заранее спасибо!

Владислав,
Project manager компании Uployal

**Comment by Anton-Grebenkin** [comment]
Посмотрите [здесь](https://github.com/iiko/front.api.sdk/issues/219), возможно поможет.

**Comment by vcpp** [comment]
> такая ошибка только на 1 заведении, а на другом все успешно работает.

Значит, можно поискать отличия в настройках, в сценарии работы и т. п.

> Failed to write to an IPC Port: Идет закрытие канала.

Сама по себе эта ошибка неинформативна, она является следствием другой ошибки, произошедшей ранее. Исходную ошибку можно искать в логах и в журнале событий Windows. В некоторых случаях ошибку проще обнаружить непосредственно в коде. Можете прикрепить логи (папку Logs целиком), журналы событий Windows (Application, System) и исходники плагина прямо сюда, только учитывайте, что эти файлы сможет посмотреть кто угодно. Если необходима конфиденциальность, перешлите эти файлы через техподдержку.
