### ISSUE TITLE
Конфликт ddl зависимостей. 

### ISSUE THREAD

**Issue by AlexDragonLore** [iiko/front.api.sdk#328]
Добрый день столкнулись с проблемой, при подключении библиотек процесс Плагин валится, когда задействует библиотеки, которые используются в плагин и в iikoFront. Например, для работы с очередью нам нужно подключить Azure.Messaging.ServiceBus, эта библиотека тянет за собой ряд бибилотек, и эти библиотеки тянут искомые 2 
```
System.Runtime.CompilerServices.Unsafe и System.Threading.Tasks.Extensions. Пробовали явно указывть в app.config
<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.5.4.0" />
		<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.5.0"/>
```

И обычно этот способ помогает, возможно проблема с вложенностью этих библиотек.
Так же не понимаю почему происходят конфликты, если плагин запускается в своем домене, в котором зависимости должны быть свои, однако, все равно происходят конфликты, логи прилагаю
```
UnhandledException in host domain:
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Threading.Tasks.ValueTask`1.get_IsCompleted()
   at Azure.Messaging.ServiceBus.ServiceBusSender.<CreateMessageBatchAsync>d__29.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
---> (Inner Exception #0) System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Threading.Tasks.ValueTask`1.get_IsCompleted()
   at Azure.Messaging.ServiceBus.ServiceBusSender.<CreateMessageBatchAsync>d__29.MoveNext()
```
[logs.zip](https://github.com/iiko/front.api.sdk/files/8068812/logs.zip)

**Comment by igorpooh1978** [comment]
поставьте dotPeek и отследите все зависимости System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1

**Comment by vcpp** [comment]
Тут скорее не dotPeek нужен, а [fuslog](https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx) или какой-нибудь модный [Fusion++](https://github.com/awaescher/Fusion). Так мы узнаем, кто ищет, что ищет, где ищет и почему считает неподходящим то, что лежит под носом :-)

Будет совсем здорово, если сможете поделиться минимальным примером воспроизведения.

> Так же не понимаю почему происходят конфликты, если плагин запускается в своем домене

Вероятно, другая версия загружается в домен плагина вместе с Reactive Extensions.
Включите логирование всех поисков и загрузок, так мы увидим и успешные, и неуспешные загрузки.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
