### ISSUE TITLE
Печать данных на чеке не работает

### ISSUE THREAD

**Issue by afinderfall** [iiko/front.api.sdk#400]
Я не понимаю, как нужно печатать данные.
Делаю вот так:

![image](https://user-images.githubusercontent.com/33827989/188898105-4c38738a-7b78-4406-a59a-6ab17e3683f1.png)

Падает ошибка
`Ошибка: System.Runtime.Remoting.RemotingException: Failed to connect to an IPC Port: The system cannot find the file specified.
 

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.IDisposable.Dispose()
   at RestoFront.Trinity.TrinityPlugin.Dispose()
[2022-09-07 19:59:12,297]  INFO [ 1] - Ошибка: System.Runtime.Remoting.RemotingException: Failed to connect to an IPC Port: The system cannot find the file specified.
 

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.IDisposable.Dispose()
   at RestoFront.Trinity.TrinityPlugin.Dispose()`

**Comment by vcpp** [comment]
Это явно не единственная ошибка. Посмотрите, что есть в _error.log_ и в _api.log_.
Попробуйте также сузить круг возможных причин, проверив отдельно печать таблицы и отдельно печать QR-кода.

**Comment by vcpp** [comment]
Задача закрыта по таймауту неактивности. Если проблема актуальна, надо будет предоставить дополнительную информацию, ответить на вопросы из предыдущих комментариев.
