### ISSUE TITLE
Как узнать потраченные бонусы при печати пречека

### ISSUE THREAD

**Issue by HakobyanAram** [iiko/front.api.sdk#436]
Мы реализуем систему лояльности. После сканирования карты клиент может платить бонусными балами. Для этого мы исползуем внешний тип оплаты. 
```c#
 private void ApplyBonus(decimal bonus, string waiterPin, IOrder order, IPaymentItem paymentItem, IOperationService operationService)
        {
            ICredentials credentials = operationService.AuthenticateByPin(waiterPin);
            order = operationService.GetOrderById(order.Id);
            operationService.ChangePaymentItemSum(bonus, 0, bonus, paymentItem, order, credentials);
        }
``` 
т.е. для сканирования карты нужно войти в кассу `Внишний тип оплаты` затем открываем окно для сканирования.  Все это реализовано в имплементации `IPaymentProcessor`. 

Получили запрос, чтобы при печати пречека оторбражать количество потраченых бонусов. Однако `Печать пречека` находится в окне `Заказ`. При выходе из `Кассы` в окно `Заказ`  Все не проведенные оплаты удаляются и не могу узнать количество потраченных бонусов. 
![image](https://user-images.githubusercontent.com/51437851/232245527-b3978f7c-855e-4316-88d9-a9ed5825ebe7.png)

Попытался решить проблему с использованием добавления кнопки в заказ, Т.е. при нажатии на кнопку отркыть окно сканировани карты, а затем применить бонусы
```c#
_subscriptions.Push(PluginContext.Operations.AddButtonToOrderEditScreen("Тест",x=>
            {
                ShowScanDialog();
               ICredentials credentials = x.os.AuthenticateByPin(GetWaiterPin());
                x.os.ChangePaymentItemSum(GetBonous(), 0, GetBonous(), paymentItem, x.order, credentials);
           }, IikoIcon));
``` 
Но здесь не могу полуучить `IPaymentItem `. 

Как могу решить эту задачу? Как оторбражать количество потраченых бонусов в пречеке?

**Comment by HakobyanAram** [comment]
Кто может ответить на этот вопрос?

**Comment by shaknail** [comment]
Добрый день
1) На экране заказа кнопка - все верно
2) После считывания карты - запоминаем в какое-нибудь хранилище (связка заказ-клиент)
3) Делаем подписку на печать пречека:
subscriptions.Push(PluginContext.Notifications.BillChequePrinting.Subscribe(BillChequePrinting));
И в этом методе, зная карту, можем печатать, сколько бонусов к списанию и т.д. и т.п.
4) А добавлять тип оплаты надо немного по другому:
- нужно запомнить IPaymentProcessor, который создается в конструкторе для регистрации типа оплаты
- Воспользоваться методом PluginContext.Operations.GetActivePaymentTypes(paymentProcessor)?.FirstOrDefault(), чтобы получить тип оплаты и потом вызвать следующие методы:

var editSession = operations.CreateEditSession(); 
var item = editSession.AddPaymentItem(sum, null, type, order);
editSession.ChangePaymentItemSum(sum, min, max, item, order);
operations.SubmitChanges(operations.AuthenticateByPin("12344321"), editSession);

Надеюсь, это поможет

**Comment by HakobyanAram** [comment]
@shaknail Спасибо за ответ.

> Воспользоваться методом PluginContext.Operations.GetActivePaymentTypes(paymentProcessor)?.FirstOrDefault(), чтобы получить тип оплаты и потом вызвать следующие методы:

попробовал  использовать тип оплаты как вы предолжили, но получил исключение 
<details>
System.Runtime.Remoting.RemotingException: Невозможно преобразовать тип аргумента "System.MarshalByRefObject" в тип параметра "System.String". ---> System.InvalidCastException: Объект должен реализовывать интерфейс IConvertible.
   в System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   в System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   --- Конец трассировки внутреннего стека исключений ---

Server stack trace: 
   в System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   в System.Runtime.Remoting.Messaging.Message.CoerceArgs(MethodBase mb, Object[] args, ParameterInfo[] pi)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationServiceInternal.GetActivePaymentTypes(IPaymentProcessor processor)
   at Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.GetActivePaymentTypes(IPaymentProcessor processor)
   at ikko.MyPlugin.Plugin.<>c__DisplayClass10_0.<.ctor>b__1(ValueTuple`3 x)
   at Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   в Resto.Front.Api.V7.OperationServiceInternal.<>c__DisplayClass522_0.<AddButtonToOrderEditScreen>b__0(ValueTuple`2 x, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 3354
   в Resto.Front.Api.PluginButtonCollection`1.<>c__DisplayClass6_0.<AddLegacy>b__0(TCallbackArgs arg, ValueTuple`4 _, Action`1 msg) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.cs:строка 43
   в Resto.Front.Api.PluginButtonCollection`1.PluginButton`1.OnClick(T args, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.PluginButton.cs:строка 113
[20
</details>
затем попробовал без `MarshalByRefObject` 

```
public class MyPayment :  IPaymentProcessor, IDisposable
{
}
```
тогда получил исключение 
<details>

is not marked as serializable.

Server stack trace: 
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.<>c__DisplayClass9_0.<GetSerializableMembers>b__0(MemberHolder _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SerializeMessage(IMessage msg, ITransportHeaders& headers, Stream& stream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationServiceInternal.GetActivePaymentTypes(IPaymentProcessor processor)
   at Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.GetActivePaymentTypes(IPaymentProcessor processor)
   at ikko.MyPlugin.Plugin.<>c__DisplayClass10_0.<.ctor>b__1(ValueTuple`3 x)
   at Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   в Resto.Front.Api.V7.OperationServiceInternal.<>c__DisplayClass522_0.<AddButtonToOrderEditScreen>b__0(ValueTuple`2 x, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 3354
   в Resto.Front.Api.PluginButtonCollection`1.<>c__DisplayClass6_0.<AddLegacy>b__0(TCallbackArgs arg, ValueTuple`4 _, Action`1 msg) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.cs:строка 43
   в Resto.Front.Api.PluginButtonCollection`1.PluginButton`1.OnClick(T args, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.PluginButton.cs:строка 113
</details>
затем попробовал получить `PaymentType` с использованием метода `GetPaymentTypes`

```
 var patymetnType= operation.GetPaymentTypes().FirstOrDefault(type=>type.Name==MyPayment.PaymentName).;
```

Но получил исключение при вызове метода 

```
operation.SubmitChanges( operation.AuthenticateByPin(Pin), editSession);
       
```

<details>
Resto.Front.Api.Exceptions.EntityAlreadyInUseException: One or more objects used in edit session are already in use.

Server stack trace: 
   в Resto.Front.Api.V7.Editors.EditSessionWriter.LockEntities(ILockedObjectsToken lockedObjectsToken) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Editors\EditSessionWriter.cs:строка 109
   в Resto.Front.Api.V7.OperationServiceInternal.SubmitChanges(IUser user, IEditSession editSession) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 1952
   в Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:строка 2473
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationServiceInternal.SubmitChanges(ICredentials credentials, IEditSession editSession)
   at Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.SubmitChanges(ICredentials credentials, IEditSession editSession)
   at ikko.MyPlugin.Plugin.<>c.<.ctor>b__10_1(ValueTuple`3 x)
   at Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   в Resto.Front.Api.V7.OperationServiceInternal.<>c__DisplayClass522_0.<AddButtonToOrderEditScreen>b__0(ValueTuple`2 x, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 3354
   в Resto.Front.Api.PluginButtonCollection`1.<>c__DisplayClass6_0.<AddLegacy>b__0(TCallbackArgs arg, ValueTuple`4 _, Action`1 msg) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.cs:строка 43
   в Resto.Front.Api.PluginButtonCollection`1.PluginButton`1.OnClick(T args, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.PluginButton.cs:строка 113
</details>

**Comment by shaknail** [comment]
Можете прислать прямо полностью ваш код? Куда-нибудь файлом скиньте и дайте ссылку

**Comment by HakobyanAram** [comment]
> Можете прислать прямо полностью ваш код? Куда-нибудь файлом скиньте и дайте ссылку

Вот тут проект

[iikoPrecheck.zip](https://github.com/iiko/front.api.sdk/files/12232592/iikoPrecheck.zip)

**Comment by HakobyanAram** [comment]
@shaknail Если в папке с плагином находится ՝Resto.Front.Api.V7.dll՝ (версия 7,9,6015,0) получаю исключение. Без dll все работает. 
В чем может быть причина?


<Details>
Невозможно преобразовать тип аргумента "System.MarshalByRefObject" в тип параметра "System.String". ---> System.InvalidCastException: Объект должен реализовывать интерфейс IConvertible.
   в System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   в System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   --- Конец трассировки внутреннего стека исключений ---

Server stack trace: 
   в System.Runtime.Remoting.Messaging.Message.CoerceArg(Object value, Type pt)
   в System.Runtime.Remoting.Messaging.Message.CoerceArgs(MethodBase mb, Object[] args, ParameterInfo[] pi)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationServiceInternal.GetActivePaymentTypes(IPaymentProcessor processor)
   at Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.GetActivePaymentTypes(IPaymentProcessor processor)
   at ikko.iikoPrecheck.Plugin.<>c__DisplayClass1_0.<.ctor>b__0(ValueTuple`3 tuple)
   at Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.RemotingHelpers.RemotableAction`1.Invoke(T arg)
   в Resto.Front.Api.V7.OperationServiceInternal.<>c__DisplayClass522_0.<AddButtonToOrderEditScreen>b__0(ValueTuple`2 x, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:строка 3354
   в Resto.Front.Api.PluginButtonCollection`1.<>c__DisplayClass6_0.<AddLegacy>b__0(TCallbackArgs arg, ValueTuple`4 _, Action`1 msg) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.cs:строка 43
   в Resto.Front.Api.PluginButtonCollection`1.PluginButton`1.OnClick(T args, Action`1 changeMessage) в F:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\PluginButtonCollection.PluginButton.cs:строка 113
</Details>

**Comment by ierof** [comment]
в папку с плагином не надо класть `Resto.Front.Api.V7.dll`, библиотеки API резолвятся из корня около iikoFront.exe и не должны меняться относительно инсталлированных версий
