### ISSUE TITLE
Cannot close order fast.

### ISSUE THREAD

**Issue by dn110779nag** [iiko/front.api.sdk#458]
При попытке оплатить заказ
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.<>c__DisplayClass20_0.<processOrdersForNewStatus>b__0(IOperationService operations) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 387

получаю ошибку
Resto.Front.Api.Exceptions.PaymentActionFailedException: Payment of order #65278 (cb1ad6ba-9002-4f7b-b995-20cb3e46673d) failed. Cannot close order fast.

<details><summary>
состояние заказа и полный трейс ошибки прилагается
</summary>

```
[2023-07-21 12:26:17,257]  INFO [32] - [FQIYvE] Данные заказа перед оплатой: cb1ad6ba-9002-4f7b-b995-20cb3e46673d => var order = new Order
{
  FullSum = 1023.00m,
  ResultSum = 1023.00m,
  Discounts = new List<IDiscountItem>
  {
  },
  AppliedDiscounts = new List<IAppliedDiscountItem>
  {
  },
  CustomerIds = new List<Guid>
  {
  },
  Guests = new List<IOrderGuestItem>
  {
    new OrderGuestItem
    {
      Name = "Гість 1",
      Rank = 0,
      Id = new Guid("1120b537-6d3a-4388-aa6d-3b1e93057fda")
    },
    new OrderGuestItem
    {
      Name = "Гість 2",
      Rank = 1,
      Id = new Guid("53201883-452a-4574-bc04-c302e0861e15")
    }
  },
  Items = new List<IOrderRootItem>
  {
    new OrderProductItem
    {
      Product = new Product
      {
        Name = "Благодійний фонд \"Місто Добра\"",
        Price = 3.0000m,
        CanSetOpenPrice = false,
        Type = ProductType.Dish,
        Category = new ProductCategory
        {
          Name = "Бар НЕалкоголь",
          Id = new Guid("99ce9a85-5469-883e-0172-eb08343a440b")
        },
        IsActive = true,
        Number = "0489780",
        ExpirationTime = null,
        Scale = null,
        Template = null,
        TaxPercent = null,
        MeasuringUnitName = "порц",
        RateSchedule = null,
        FastCode = "11192",
        ImmediateCookingStart = false,
        Id = new Guid("0c0c082d-c065-4f99-9b01-b1f5dc95bb45")
      },
      Price = 3.00m,
      Cost = 3.00m,
      OpenPrice = null,
      IsPricePredefined = false,
      ResultSum = 3.00m,
      TaxPercent = null,
      AssignedModifiers = new List<IOrderModifierItem>
      {
      },
      Amount = 1m,
      CookingStartTime = DateTime.ParseExact("2023-07-21T11:46:52.3720000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingFinishTime = DateTime.ParseExact("2023-07-21T11:48:30.0790000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingTime = TimeSpan.ParseExact("00:10:00", "c", CultureInfo.InvariantCulture, TimeSpanStyles.None),
      ServeTime = DateTime.ParseExact("2023-07-21T11:48:30.0790000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Comment = null,
      Course = OrderItemCourse.First,
      Size = null,
      Guest = new OrderGuestItem
      {
        Name = "Гість 1",
        Rank = 0,
        Id = new Guid("1120b537-6d3a-4388-aa6d-3b1e93057fda")
      },
      PrintTime = DateTime.ParseExact("2023-07-21T11:46:52.3720000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Status = OrderItemStatus.Served,
      Deleted = false,
      DeletionMethod = null,
      Waiter = new User
      {
        Name = "Коженьовський Роман",
        Type = UserType.Employee,
        IsSessionOpen = true,
        CellPhone = "+380507175415\n",
        Card = "298084",
        Code = "600026838",
        TaxpayerId = "",
        InsuranceNumber = "",
        Id = new Guid("d32ba3dd-cafe-4d64-87b4-df421c6f4cb7")
      },
      Id = new Guid("30dd6539-b7f4-4fbe-b045-073669343011")
    },
    new OrderProductItem
    {
      Product = new Product
      {
        Name = "Бургер EPIC CHEESEBURGER V - 1.0.",
        Price = 370.0000m,
        CanSetOpenPrice = false,
        Type = ProductType.Dish,
        Category = new ProductCategory
        {
          Name = "Кухня",
          Id = new Guid("99ce9a85-5469-883e-0172-eb08343a4407")
        },
        IsActive = true,
        Number = "98765434567898546223",
        ExpirationTime = null,
        Scale = null,
        Template = null,
        TaxPercent = null,
        MeasuringUnitName = "порц",
        RateSchedule = null,
        FastCode = "21247387",
        ImmediateCookingStart = false,
        Id = new Guid("a95a70a4-0eeb-439f-849b-2efbc114efa5")
      },
      Price = 370.00m,
      Cost = 740.00m,
      OpenPrice = null,
      IsPricePredefined = false,
      ResultSum = 740.00m,
      TaxPercent = null,
      AssignedModifiers = new List<IOrderModifierItem>
      {
      },
      Amount = 2m,
      CookingStartTime = DateTime.ParseExact("2023-07-21T11:46:52.3720000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingFinishTime = DateTime.ParseExact("2023-07-21T11:56:55.1980000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingTime = TimeSpan.ParseExact("00:10:00", "c", CultureInfo.InvariantCulture, TimeSpanStyles.None),
      ServeTime = DateTime.ParseExact("2023-07-21T11:57:04.4060000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Comment = null,
      Course = OrderItemCourse.First,
      Size = null,
      Guest = new OrderGuestItem
      {
        Name = "Гість 1",
        Rank = 0,
        Id = new Guid("1120b537-6d3a-4388-aa6d-3b1e93057fda")
      },
      PrintTime = DateTime.ParseExact("2023-07-21T11:46:52.3720000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Status = OrderItemStatus.Served,
      Deleted = false,
      DeletionMethod = null,
      Waiter = new User
      {
        Name = "Коженьовський Роман",
        Type = UserType.Employee,
        IsSessionOpen = true,
        CellPhone = "+380507175415\n",
        Card = "298084",
        Code = "600026838",
        TaxpayerId = "",
        InsuranceNumber = "",
        Id = new Guid("d32ba3dd-cafe-4d64-87b4-df421c6f4cb7")
      },
      Id = new Guid("38896a93-d6c3-42c3-bde0-9b50ad7568e1")
    },
    new OrderProductItem
    {
      Product = new Product
      {
        Name = "Напій Coca-cola 0,2л (epic)",
        Price = 70.0000m,
        CanSetOpenPrice = false,
        Type = ProductType.Dish,
        Category = new ProductCategory
        {
          Name = "Бар НЕалкоголь",
          Id = new Guid("99ce9a85-5469-883e-0172-eb08343a440b")
        },
        IsActive = true,
        Number = "45465467949516790244",
        ExpirationTime = null,
        Scale = null,
        Template = null,
        TaxPercent = null,
        MeasuringUnitName = "порц",
        RateSchedule = null,
        FastCode = "13221",
        ImmediateCookingStart = false,
        Id = new Guid("97611178-b116-46ae-9bfb-cf67a597e451")
      },
      Price = 70.00m,
      Cost = 140.00m,
      OpenPrice = null,
      IsPricePredefined = false,
      ResultSum = 140.00m,
      TaxPercent = null,
      AssignedModifiers = new List<IOrderModifierItem>
      {
      },
      Amount = 2m,
      CookingStartTime = DateTime.ParseExact("2023-07-21T11:46:52.3720000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingFinishTime = DateTime.ParseExact("2023-07-21T11:48:29.8760000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingTime = TimeSpan.ParseExact("00:10:00", "c", CultureInfo.InvariantCulture, TimeSpanStyles.None),
      ServeTime = DateTime.ParseExact("2023-07-21T11:48:29.8760000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Comment = null,
      Course = OrderItemCourse.First,
      Size = null,
      Guest = new OrderGuestItem
      {
        Name = "Гість 1",
        Rank = 0,
        Id = new Guid("1120b537-6d3a-4388-aa6d-3b1e93057fda")
      },
      PrintTime = DateTime.ParseExact("2023-07-21T11:46:52.3720000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Status = OrderItemStatus.Served,
      Deleted = false,
      DeletionMethod = null,
      Waiter = new User
      {
        Name = "Коженьовський Роман",
        Type = UserType.Employee,
        IsSessionOpen = true,
        CellPhone = "+380507175415\n",
        Card = "298084",
        Code = "600026838",
        TaxpayerId = "",
        InsuranceNumber = "",
        Id = new Guid("d32ba3dd-cafe-4d64-87b4-df421c6f4cb7")
      },
      Id = new Guid("91d72de8-9c5d-401a-9583-3022dee942e2")
    },
    new OrderProductItem
    {
      Product = new Product
      {
        Name = "Напій Coca-cola 0,2л (epic)",
        Price = 70.0000m,
        CanSetOpenPrice = false,
        Type = ProductType.Dish,
        Category = new ProductCategory
        {
          Name = "Бар НЕалкоголь",
          Id = new Guid("99ce9a85-5469-883e-0172-eb08343a440b")
        },
        IsActive = true,
        Number = "45465467949516790244",
        ExpirationTime = null,
        Scale = null,
        Template = null,
        TaxPercent = null,
        MeasuringUnitName = "порц",
        RateSchedule = null,
        FastCode = "13221",
        ImmediateCookingStart = false,
        Id = new Guid("97611178-b116-46ae-9bfb-cf67a597e451")
      },
      Price = 70.00m,
      Cost = 140.00m,
      OpenPrice = null,
      IsPricePredefined = false,
      ResultSum = 140.00m,
      TaxPercent = null,
      AssignedModifiers = new List<IOrderModifierItem>
      {
      },
      Amount = 2m,
      CookingStartTime = DateTime.ParseExact("2023-07-21T12:08:09.8880000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingFinishTime = DateTime.ParseExact("2023-07-21T12:18:10.6710000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      CookingTime = TimeSpan.ParseExact("00:10:00", "c", CultureInfo.InvariantCulture, TimeSpanStyles.None),
      ServeTime = DateTime.ParseExact("2023-07-21T12:23:12.8570000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Comment = null,
      Course = OrderItemCourse.First,
      Size = null,
      Guest = new OrderGuestItem
      {
        Name = "Гість 1",
        Rank = 0,
        Id = new Guid("1120b537-6d3a-4388-aa6d-3b1e93057fda")
      },
      PrintTime = DateTime.ParseExact("2023-07-21T12:08:09.8880000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
      Status = OrderItemStatus.Served,
      Deleted = false,
      DeletionMethod = null,
      Waiter = new User
      {
        Name = "Коженьовський Роман",
        Type = UserType.Employee,
        IsSessionOpen = true,
        CellPhone = "+380507175415\n",
        Card = "298084",
        Code = "600026838",
        TaxpayerId = "",
        InsuranceNumber = "",
        Id = new Guid("d32ba3dd-cafe-4d64-87b4-df421c6f4cb7")
      },
      Id = new Guid("849ef32e-234c-4be0-8f21-38cebc8f6777")
    }
  },
  Payments = new List<IPaymentItem>
  {
    new PaymentItem
    {
      Sum = 1023.00m,
      MinSum = null,
      MaxSum = null,
      Status = PaymentStatus.New,
      AdditionalData = new CardPaymentItemAdditionalData
      {
        CardNumber = "cb1ad6ba-9002-4f7b-b995-20cb3e46673d"
      },
      Type = new PaymentType
      {
        Name = "Shake to Pay by monobank",
        IsCombinable = false,
        Kind = PaymentTypeKind.Card,
        IsEnabled = true,
        IsHidden = false,
        CanDisplayChange = false,
        DiscountType = null,
        CanBeExternalProcessed = true,
        OpenCashDrawerOnPay = false,
        Id = new Guid("9c17e9bd-dec5-4d13-a34f-407c92707f2d")
      },
      DonationType = null,
      IsPreliminary = false,
      IsExternal = true,
      IsFiscalizedExternally = false,
      IsProcessedExternally = true,
      IsPrepay = false,
      PointOfSale = null,
      OrganizationDetailsInfo = null,
      Id = new Guid("2385eef5-efa9-41d7-b4f8-7f4eb405e6c8")
    }
  },
  Donations = new List<IPaymentItem>
  {
  },
  Status = OrderStatus.Bill,
  OpenTime = DateTime.ParseExact("2023-07-21T11:46:46.0280000+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
  BillTime = DateTime.ParseExact("2023-07-21T12:26:16.3257811+03:00", "O", CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind),
  CloseTime = null,
  RepeatBillNumber = 0,
  FiscalChequeNumber = null,
  Number = 65278,
  Waiter = new User
  {
    Name = "Коженьовський Роман",
    Type = UserType.Employee,
    IsSessionOpen = true,
    CellPhone = "+380507175415\n",
    Card = "298084",
    Code = "600026838",
    TaxpayerId = "",
    InsuranceNumber = "",
    Id = new Guid("d32ba3dd-cafe-4d64-87b4-df421c6f4cb7")
  },
  Cashier = null,
  IsBanquetOrder = false,
  ProcessedPaymentsSum = 1023.00m,
  EstimatedGuestsCount = 2,
  OrderType = null,
  OriginName = null,
  Comment = null,
  PricingTime = null,
  Combos = new List<IOrderCombo>
  {
  },
  IikoCard51Info = new IikoCard51OrderInfo
  {
    Coupon = null,
    AppliedManualConditions = new List<Guid>
    {
    },
    HasFixedDiscounts = false,
    DynamicDiscounts = new Dictionary<Guid, decimal>
    {
    }
  },
  WasPrepaid = false,
  IsTopCookingPriority = false,
  CookingPriority = 0,
  PriceCategory = null,
  TabName = null,
  StornedOrderId = null,
  LastChangedTerminalId = new Guid("3a4ae928-d9a6-375e-0185-ea6edb3ed42a"),
  Revision = 932101,
  Id = new Guid("cb1ad6ba-9002-4f7b-b995-20cb3e46673d"), Tables= new List<ITable>
{
  new Table
  {
    Number = 18,
    Name = "Балкон",
    SeatingCapacity = 0,
    IsActive = true,
    RestaurantSection = new RestaurantSection
    {
      Name = "Epic 2й поверх",
      Id = new Guid("9686b59e-d734-42d1-aca6-119729b73470")
    },
    Id = new Guid("e5f0e981-e771-43a7-888e-201a97409c77")
  }
};



[2023-07-21 12:26:17,701] ERROR [32] - [FQIYvE] После первой попытки оплаты ордера cb1ad6ba-9002-4f7b-b995-20cb3e46673d получили ошибку: Payment of order #65278 (cb1ad6ba-9002-4f7b-b995-20cb3e46673d) failed. Cannot close order fast.

Resto.Front.Api.Exceptions.PaymentActionFailedException: Payment of order #65278 (cb1ad6ba-9002-4f7b-b995-20cb3e46673d) failed. Cannot close order fast.

Server stack trace: 
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1088
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1128
   at Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:line 2687
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo)
   at Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7\OperationsInterfaces.g.cs:line 4533
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.PayOrderWithBillIfRequired(Guid orderId, ICredentials credentials) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 672
[2023-07-21 12:26:17,704] ERROR [32] - [FQIYvE] Can't pay order!
Resto.Front.Api.Exceptions.PaymentActionFailedException: Payment of order #65278 (cb1ad6ba-9002-4f7b-b995-20cb3e46673d) failed. Cannot close order fast.

Server stack trace: 
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1088
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1128
   at Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:line 2687
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.PayOrderWithBillIfRequired(Guid orderId, ICredentials credentials) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 699
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.paySplitedOrder(Guid orderId, CardPaymentItemAdditionalData additionalData) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 710
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.<>c__DisplayClass20_0.<processOrdersForNewStatus>b__0(IOperationService operations) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 387
[2023-07-21 12:26:17,705] ERROR [25] - [FQIYvE] ... payBill {rId: 2023-07-21 12:26:13.439203938#hj1if4I, billId: cb1ad6ba-9002-4f7b-b995-20cb3e46673d, sum: 1023,00, orderNumbers: 1023,00 finish with exception: 
Resto.Front.Api.monoPayment.PayException ---> Resto.Front.Api.Exceptions.PaymentActionFailedException: Payment of order #65278 (cb1ad6ba-9002-4f7b-b995-20cb3e46673d) failed. Cannot close order fast.

Server stack trace: 
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1088
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1128
   at Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:line 2687
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.PayOrderWithBillIfRequired(Guid orderId, ICredentials credentials) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 699
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.paySplitedOrder(Guid orderId, CardPaymentItemAdditionalData additionalData) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 710
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.<>c__DisplayClass20_0.<processOrdersForNewStatus>b__0(IOperationService operations) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 387
   --- End of inner exception stack trace ---
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.processOrdersForNewStatus(String rId, String billId, Decimal sum, FiscalDataRow[] fiscalData) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 449
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.performLogicByOrderStatus(String rId, String billId, Decimal sum, FiscalDataRow[] fiscalData) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 228
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.payBill(String rId, String billId, Nullable`1 sum, FiscalDataRow[] fiscalData) in /src/client/mono/processors/logic/pay/PayOrderLogic.cs:line 62
   at Resto.Front.Api.monoPayment.mono.processors.logic.pay.PayOrderLogicProvider.payBill(String rId, String billId, Nullable`1 sum, FiscalDataRow[] fiscalData) in /src/client/mono/processors/logic/pay/PayOrderLogicProvider.cs:line 30
   at Resto.Front.Api.monoPayment.mono.processors.logic.handlers.PayBillCommandHandler.HandleCommand(BasePayload payload) in /src/client/mono/processors/logic/handlers/PayBillCommandHandler.cs:line 46
```
</details>

**Comment by vcpp** [comment]
К сожалению, это общая ошибка на «все остальные» случаи. Чтобы понять причину, надо смотреть собственные логи приложения (_cash-server.log_ и другие). Поищите там записи по id вашего заказа и по времени попытки оплаты. Если не получится локализовать самостоятельно, надо будет прислать логи для анализа нам.

При наличии в логах конфиденциальной информации лучше передавать их через техподдержку, а не здесь.
