### ISSUE TITLE
.Net Framework конфликт с версиями плагина и системы

### ISSUE THREAD

**Issue by Martipia-Platform** [iiko/front.api.sdk#471]
Здравствуйте!

Мы написали плагин с **target .Net Framework = 4.7.2** как и написано в документации, но мы встретили проблему когда пытались установить плагин у клиента с **iikoRMS front 8.4.6**. В логах говорит что программа не разрешает загрузить наш плагин потому что мы пытаемся использовать более старую версию .Net Framework. И действительно, у клиента установленна версия **.Net Framework 4.8**.

Вопрос - какую версию нам использовать? Это наш плагин неправильный target поставил? Или у клиента надо поставить другую версию .Net Framework? Или вообще сделать multi-targetting и попытаться на несколько версий?

Спасибо!

Ошибка из логов:

> [2023-08-30 20:29:12,699] ERROR [ 1] - Couldn't load plugin type, loader thrown an exception:
> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files\iiko\iikoRMS front 8.4.6\Front.Net\Plugins\MartipiaTipAndRate\MartipiaTipAndRate.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
> File name: 'file:///C:\Program Files\iiko\iikoRMS front 8.4.6\Front.Net\Plugins\MartipiaTipAndRate\MartipiaTipAndRate.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at Resto.Front.Api.Host.PluginRunner.TryGetPluginType(String assemblyPath, String className) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Api\Resto.Front.Api.Host\PluginRunner.cs:line 180

**Comment by Martipia-Platform** [comment]
Тысяча извинений, ошибка была в самой системе. Если у кого-то также - была проблема в том что наш плагин загрузили из интернета в файле .zip и его (файл) надо было "разблокировать" прежде чем использовать внутренние файлы плагина.
