### ISSUE TITLE
Проблема при добавлении информации при печати кассового чека

### ISSUE THREAD

**Issue by pipikonda** [iiko/front.api.sdk#510]
Разрабатываем плагин для ресторанов используем sdk api v7. После обнвления на версию 8.8.7013.0
При попытке добавить информацию в чек сталкиваемся с аномалиями

При инициализации плагина, подписываемся на события
`PluginContext.Notifications.CashChequePrinting.Subscribe(ExtendCheck);`

Внутри метода ExtendCheck возвращаем 
`
return new CashCheque()
                {
                    AfterCheque = doc
                };
`
где doc это                `var doc = new XElement(Tags.Doc);` с текстовым содержанием. 
При попытке вернуть из метода текст для чека, получаем ошибку от SDK.

Стектрейс:
```
System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace: 
   at Resto.CashServer.Services.CashRegisterService.SetChequeText(ChequeTask task, CashRegisterChequeExtensions chequeExtensions, ICashRegister cashRegister, ChequePrinterDriver driver) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\CashRegisterService.cs:line 261
   at Resto.CashServer.Agent.Print.ChequePrinterDriverHelper.DoCheque(ICashRegister device, ChequeTask chequeTask, ChequeAdditionalInfo chequeAdditionalInfo, ILongRunningOperation operation, CashRegisterChequeExtensions chequeExtensions, IOrderPrices orderPrices, ILockedObjectsToken token) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Agent\Print\ChequePrinterDriverHelper.cs:line 66
   at Resto.CashServer.Services.CashRegisterService.<>c__DisplayClass51_0.<PrintCheque>b__4(ICashRegister cr, ChequeTask task) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\CashRegisterService.cs:line 221
   at Resto.CashServer.Services.OperationVerifier.CashRegisterOperationVerifier.DoCashRegisterAction(Func`1 cashRegisterAction, ILongRunningOperation operation, CashRegisterTask task, Boolean skipDuplicateCheck, IUser cashier, CashRegisterResult cachedCashRegisterResult) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OperationVerifier\CashRegisterOperationVerifier.cs:line 117
   at Resto.CashServer.Services.CashRegisterService.ExecuteSerialOperation[TTask](ICashRegister cashRegister, TTask task, IUser cashier, CashRegisterOperationVerifier operationVerifier, ILongRunningOperation operation, Func`3 cashRegisterAction, Boolean skipDuplicateCheck, Boolean checkSerialNumber) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\CashRegisterService.cs:line 1122
   at Resto.CashServer.Services.CashRegisterService.ExecuteSerialOperationWithExternalProcessors[TTask](ICashRegister cashRegister, TTask task, IUser cashier, ILongRunningOperation operation, Action`2 beforeOperation, Func`3 cashRegisterAction, Action`3 afterOperation, Boolean skipDuplicateCheck, Boolean checkSerialNumber) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\CashRegisterService.cs:line 1058
   at Resto.CashServer.Services.CashRegisterService.PrintCheque(ICashRegister cashRegister, IBaseOrder order, IReadOnlyCollection`1 paymentTransactions, Nullable`1 nonCashChange, ICashDrawer externalCashDrawer, Boolean needHideOnCashRegister, IOrderPrices orderPrices, IReadOnlyCollection`1 paymentDiscounts, ILockedObjectsToken token, OrganizationDetailsInfo organizationDetails, ChequeAdditionalInfo chequeAdditionalInfo, TaxationSystem taxationSystem, Boolean needOpenDrawer, Boolean suggestRepeatOnError, Boolean isPaymentTypeFastReplacement, Boolean isNeedPrintEInvoiceCheque) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\CashRegisterService.cs:line 216
   at Resto.CashServer.Services.OrderService.CloseOrderOperation(IBaseOrderBuilder orderBuilder, ICafeSession session, IOrderCloseParameters closeParameters, ILockedObjectsToken token, Boolean suggestRepeatOnError, Boolean isPaymentTypeFastReplacement) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:line 1739
   at Resto.CashServer.Services.OrderService.ProcessOrderCloseAfterPaymentProcessing(IBaseOrderBuilder orderBuilder, ICafeSession cafeSession, IOrderCloseParameters closeParameters, ILockedObjectsToken token, Boolean suggestRepeatOnError, Boolean isPaymentTypeFastReplacement) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:line 747
   at Resto.CashServer.Services.OrderService.ProcessOrderClose(IBaseOrderBuilder orderBuilder, ICafeSession cafeSession, IOrderCloseParameters closeParameters, ILockedObjectsToken token, DelayedOrderSaver delayedSaver, IPermissionChecker permissionChecker, IBackgroundRunner backgroundRunner, CallerDeterminator determinator, Action`1 changeProgressBarMessage, Boolean printNeeded, Boolean suggestRepeatOnError, Boolean isPaymentTypeFastReplacement) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:line 647
   at Resto.CashServer.Services.OrderService.TryFastSingleOrderClose(IBaseOrderBuilder order, ICashRegister cashRegister, IUser cashier, ILockedObjectsToken token, IPermissionChecker permissionChecker, IBackgroundRunner backgroundRunner, CallerDeterminator determinator, Action`1 changeProgressBarMessage, ICashDrawer externalCashDrawer, Boolean needHideOnCashRegister, ChequeAdditionalInfo chequeAdditionalInfo, DeliveryCancellationParams deliveryCancellation, Boolean needOpenDrawer, TaxationSystem taxationSystem, Boolean isNeedPrintEInvoiceCheque, Nullable`1 closeTime, Boolean printNeeded, Boolean suggestRepeatOnError, Boolean isPaymentTypeFastReplacement) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:line 1532
   at Resto.CashServer.Services.OrderService.<>c__DisplayClass27_0.<FastOrderClose>b__0(OrderPaymentInfo o) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:line 478
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Resto.CashServer.Services.OrderService.FastOrderClose(IBaseOrderBuilder orderBuilder, IUser cashier, IPermissionChecker permissionChecker, IBackgroundRunner backgroundRunner, DeliveryCancellationParams deliveryCancellation, ILockedObjectsToken token, ICashDrawer externalCashDrawer, ICashRegister defaultCashRegister, CallerDeterminator determinator, ChequeAdditionalInfo chequeAdditionalInfo, Boolean needHideOnCashRegister, Boolean needOpenDrawer, Nullable`1 closeTime, Boolean printNeeded, Boolean suggestRepeatOnError, Boolean isPaymentTypeFastReplacement) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.cs:line 478
   at Resto.CashServer.Services.OrderService.PayOrderAndPayOutOnUser(IBaseOrderEntity order, IUser user, IPaymentType paymentType, Decimal paySum, Boolean defaultCashRegisterIfAmbiguity, ChequeAdditionalInfo chequeAdditionalInfo, ILockedObjectsToken token, CallerDeterminator determinator) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Resto.CashServer\Services\OrderService.RemotePayment.cs:line 132
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrderAndPayOutOnUser(IUser user, IBaseOrderEntity order, IPaymentType paymentType, Decimal sum, ChequeAdditionalInfo apiChequeAdditionalInfo) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1068
   at Resto.Front.Api.V7.OperationServiceInternal.PayOrder(IUser user, IBaseOrderEntity order, ChequeAdditionalInfo apiChequeAdditionalInfo) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\OperationServiceInternal.cs:line 1127
   at Resto.Front.Api.V7.OperationServiceInternal.Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api\V7\Operations.g.cs:line 2687
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.IOperationServiceInternal.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo)
   at Resto.Front.Api.OperationServiceFacade.Resto.Front.Api.IOperationService.PayOrder(ICredentials credentials, IOrder order, ChequeAdditionalInfo chequeAdditionalInfo) in L:\BuildAgent\work\master-installer\dev\iikoFront.Net\Api\Resto.Front.Api.V7\OperationsInterfaces.g.cs:line 4533
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.PayOrderWithBillIfRequired(Guid orderId, ICredentials credentials) in /builds/expirenza/core/syrve-plugin-v7/client/mono/processors/logic/pay/PayOrderLogic.cs:line 763
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.paySplitedOrder(Guid orderId, CardPaymentItemAdditionalData additionalData, List`1 gifts) in /builds/expirenza/core/syrve-plugin-v7/client/mono/processors/logic/pay/PayOrderLogic.cs:line 802
   at Resto.Front.Api.monoPayment.logic.PayOrderLogic.<>c__DisplayClass24_0.<processOrdersForNewStatus>b__0(IOperationService operations) in /builds/expirenza/core/syrve-plugin-v7/client/mono/processors/logic/pay/PayOrderLogic.cs:line 416
```

Пример наносимого текста:
```
<doc>
  <f0>ЕКВАЙЕР: Universal Bank</f0>
  <f0>ТЕРМІНАЛ: XPZ10001</f0>
  <f0>КОМІСІЯ: 0 грн.</f0>
  <f0>ВИД ОПЕРАЦІЇ: Оплата</f0>
  <f0>ЕПЗ: 55554444******16</f0>
  <f0>ПС: MC</f0>
  <f0>RRN: 111111111111</f0>
  <f0>КОД. АВТ: 222222</f0>
</doc>
```

после попытки закрыть заказ  `PluginContext.Operations.PayOrder(credentials, order);`
Со стороны syrve front 
Заказ после того как "развалился" по местам приготовления "пропадает с UI и появляется только после перезагрузки  UI фронта

**Comment by rengal** [comment]
Баг (внутренний номер RMS-56410), исправлено в 8.8.8 и 8.9.3
