### ISSUE TITLE
Краш при попытке запуска на плагина на версии Resto.Front.Api.Host ver. 6.4.1746.0

### ISSUE THREAD

**Issue by wildcherrycandy** [iiko/front.api.sdk#87]
При попытке запуска на плагина на версии Resto.Front.Api.Host ver. 6.4.1746.0
Используем пакет resto.front.api.v5\5.4.1160
Видим в логе плагина:

```
2019-08-28 19:59:36,470]  INFO [ 1] - Host process GuestMe (6584) for вЂњGuestMe.Plugin.GuestMePluginвЂќ class from вЂњC:\Program Files\iiko\iikoRMS\Front.Net\Plugins\GuestMe\GuestMe.Plugin.dllвЂќ assembly is running in background mode.
[2019-08-28 19:59:36,470]  INFO [ 1] - Plugin assembly info:
   
  GuestMe.Plugin v4.0.1.3,  (GuestMe.Plugin.dll v4.0.1.3, GuestMe.Plugin)
[2019-08-28 19:59:36,470]  INFO [ 1] - Created plugin domain вЂњGuestMeвЂќ using вЂњC:\Program Files\iiko\iikoRMS\Front.Net\Plugins\GuestMe\GuestMe.Plugin.dll.configвЂќ
[2019-08-28 19:59:36,486]  INFO [ 1] - Registering ipc channel...
[2019-08-28 19:59:36,970] ERROR [ 1] - UnhandledException in host domain:
System.ArgumentException: Object of type 'System.Runtime.Serialization.TypeLoadExceptionHolder' cannot be converted to type 'System.IServiceProvider'.

Server stack trace: 
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RtFieldInfo.UnsafeSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Runtime.Serialization.FormatterServices.SerializationSetValue(MemberInfo fi, Object target, Object value)
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryResponseMessage(Stream inputStream, IMethodCallMessage reqMsg, Boolean bStrictBinding)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.Ipc.IPluginHostingService.Connect(Int32 processId, Int32 licenseModuleId, String pluginName, IShutdownSignal shutdownSignal)
   at Resto.Front.Api.Host.PluginRunner.TryConnect(String pluginName, Int32 licenseModuleId, IShutdownSignal shutdownSignal, String serviceUri, SerializableLog log) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api.Host\PluginRunner.cs:line 135
   at Resto.Front.Api.Host.PluginRunner.Run(String assemblyPath, String className, String pluginName, Int32 moduleId, String serviceUri) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api.Host\PluginRunner.cs:line 76
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Resto.Front.Api.Host.PluginRunner.Run(String assemblyPath, String className, String pluginName, Int32 moduleId, String serviceUri)
   at Resto.Front.Api.Host.Program.Main(String[] args) in H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api.Host\Program.cs:line 40


```

Делали попытку запуска "пустого", результат аналогичный.
```

using Resto.Front.Api.V5;
using Resto.Front.Api.V5.Attributes;
using Resto.Front.Api.V5.Attributes.JetBrains;

namespace GuestMe.Plugin
{
    [UsedImplicitly]
    [PluginLicenseModuleId(21005108)]
    public class GuestMePlugin : IFrontPlugin
    {
        public GuestMePlugin()
        {
            PluginContext.Log.Info("Initializing GuestMe plugin...");
            PluginContext.Log.Info("GuestMe plugin started.");
        }

        public void Dispose()
        {
            PluginContext.Log.Info("GuestMe plugin dispose.");
        }
    }
}


```
[iikoAgent-version-Crash-20190828-19-59-44-7496.zip](https://github.com/iiko/front.api.sdk/files/3555631/iikoAgent-version-Crash-20190828-19-59-44-7496.zip)

**Comment by ierof** [comment]
А нет ли у вас "лишних" редиректов в конфиг-файле?

**Comment by allmylovingtoyou** [comment]
Спасибо, помогло почистить app.config
